/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package kotlinimpl

import kotlin.test.*;


class AppTest {
    @Test
    fun testAppHasAGreeting() {
        val classUnderTest = App()
    }
}
